name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Create config file with secrets
      run: |
        cat > config.js << EOF
        // Configuración segura - APIs ocultas
        window.API_CONFIG = {
          ASSISTANT_API_KEY: "${{ secrets.ASSISTANT_API_KEY }}",
          TRANSLATOR_API_KEY: "${{ secrets.TRANSLATOR_API_KEY }}",
          API_URL: "https://api.openrouter.ai/api/v1/chat/completions"
        };
        EOF
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
